### ISSUE TITLE
undefined: commandeer.ImplementsRunner

### ISSUE THREAD

**Issue by chrispickard** [jaffee/commandeer#6] opened 2019-03-01 15:07 UTC
I tried to run myapp-cobrafy which gives `undefined: commandeer.ImplementsRunner` at line 31 in cobrafy/cobra.go

full error
```shell
~/dev/golang/src/github.com/jaffee/commandeer/examples/myapp/cmd/myapp-cobrafy master
» go run main.go
# github.com/jaffee/commandeer/cobrafy
../../../../cobrafy/cobra.go:31:5: undefined: commandeer.ImplementsRunner
```

**Comment by jaffee** [comment] 2019-03-01 16:40
that's odd... can you make sure you have the latest version of the master branch? 

I am not able to reproduce this issue and `ImplementsRunner` is clearly defined in com.go

**Comment by chrispickard** [comment] 2019-03-01 16:50
I pulled and I'm up to date with master. The latest commit I have is `719d29f8107ee2337fef4e1680770ea58780ff32` which is the same one github shows, and I still don't have that function. I couldn't find it with the github search either (or just by looking at `com.go` on github)

**Comment by chrispickard** [comment] 2019-03-01 16:52
as far as I can tell it looks like it was removed in #4

**Comment by jaffee** [comment] 2019-03-01 17:03
ah ha! I didn't have the latest master 🤦‍♂️ 

Thank you! I pushed a fix to master

**Closed** 2019-03-01 17:20 UTC
